### ISSUE TITLE
Helpers don't work with local filesystem provider

### ISSUE THREAD

**Issue by jwoffindin** [jwoffindin/stk#7]
h2. What did you expect to happen?

A template that uses a helper when using non-git provider should work.

h2. What happened?

The template errors with a `FileNotFoundError` error trying to load the helper.

h2. Steps to reproduce

Add the following to a config file:

```yaml
# s3-cloudfront.yaml
template:
  version:
  root: ../../stk-starter-templates

helpers:
   - oidc_condition
```

then running `cfn validate s3-cloudfront test` gives the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: '../../stk-starter-templates/helpers/oidc_condition.py'
```

the file does exist however. Same issue occurs if `template.root` is an absolute file path rather than relative.
