### ISSUE TITLE
Add support for cross-region stack references

### ISSUE THREAD

**Issue by jwoffindin** [jwoffindin/stk#8]
I would like to be able to reference stacks in other regions. Add "region" to ref details to override the region the stack will be referenced in.

E.g. would like to be able to do:

```
aws:
  region: ap-southeast-2

refs:
  some_stack:
    region: us-east-1

vars:
  foo: "{{ refs.some_stack.MyOutput }}"
```
